services:
  wallet-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config.env
    ports:
      - "${WALLET_SERVER_PORT:-8080}:${WALLET_SERVER_PORT:-8080}"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:16.9-bullseye
    container_name: postgres-wallet
    env_file:
      - config.env
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-walletdb}"]
      interval: 5s
      timeout: 5s
      retries: 5
